02_create new block
Albert-SA/starter pull request #2
Opened 2023-11-02 13:21 UTC by Albert-SA

2023-11-03 07:29 UTC, andrey-kudinov requested changes

2023-11-03 07:29 UTC, andrey-kudinov commented on index.html
> +                </button>
https://ishadeed.com/article/styling-the-good-old-button/

2023-11-03 07:29 UTC, andrey-kudinov commented on index.html
> +                <div class="amway__cards__header-subtitle">
лучше добавить больше семантики
`h2`

2023-11-03 07:29 UTC, andrey-kudinov commented on index.html
> +                <div class="amway__card__header-descr">
`p`

2023-11-03 07:29 UTC, andrey-kudinov commented on index.html
> +    <div class="amway">
`section`

2023-11-03 07:29 UTC, andrey-kudinov commented on index.html
>      <div class="solutions">
`section`

2023-11-03 07:29 UTC, andrey-kudinov commented on index.html
>  <body>
```
body
  header // нет
  main
    section
    section
  footer // нет
```

2023-11-03 07:29 UTC, andrey-kudinov commented on index.html
> +                <button class="amway__card__header-btn-frst">
не совсем по **БЭМ**

2023-11-03 07:29 UTC, andrey-kudinov commented on icons/Business.png
такие элементы лучше выгружать из фигмы как `свг` так как это векторный рисунок

`вектор` vs `растор`

2023-11-03 07:29 UTC, andrey-kudinov commented on index.html
> +                <div class="amway__card__sale-subtitle">Програми підтримки продажів</div>
`h3`

2023-11-03 07:29 UTC, andrey-kudinov commented on index.html
> +                <div class="amway__card__sale-descr">Прибутковий бізнес з перших кроків!</div>
`p`

2023-11-03 07:29 UTC, andrey-kudinov commented on index.html
> +                <div class="amway__card__sale-line"></div>
у заголовка `border-bottom: 1px solid цвет`

2023-11-07 17:08 UTC, andrey-kudinov commented on index.html
> +            <div class="amway-card__header">
```
amway__cards

amway__card

amway__card-header
```

2023-11-07 17:10 UTC, andrey-kudinov commented on index.html
> +                <h2 class="amway-card__header--subtitle">
точно не модификатор

2023-11-07 17:10 UTC, andrey-kudinov commented on index.html
> +                <p class="amway-card__header--descr">
точно не модификатор

2023-11-07 17:11 UTC, andrey-kudinov commented on index.html
> +                <button class="amway-card__header--btn-second">
скорее всего не модификатор

2023-11-07 17:11 UTC, andrey-kudinov commented on css/style.css
> +.amway-card__income--img, .amway-card__sale--img, .amway-card__business--img {
в столбик

2023-11-07 19:09 UTC, Albert-SA commented
finish block2

2023-11-07 19:10 UTC, merged